### ISSUE TITLE
how to install land configure 'perl' in the wsl, ubuntu vesion is  Ubuntu 22.04.3 LTS,

### ISSUE THREAD

**Issue by feixuan666** [stapelberg/cpan-install#3]
i have used to 'which per' , but no result , i have try to add '.banshrc' also effect.  and i tried to install 'Perl' on the official website, but I was defeated.   
![image](https://github.com/stapelberg/cpan-install/assets/119277663/7f7143f8-50b5-477e-bc8d-f40caf6acf17)
![image](https://github.com/stapelberg/cpan-install/assets/119277663/c3913ee6-9c42-4b9f-985c-2229e53db2fc)
![image](https://github.com/stapelberg/cpan-install/assets/119277663/1d58ba7c-f7f9-41a6-aed4-8f22891a5628)
![image](https://github.com/stapelberg/cpan-install/assets/119277663/0f56a230-de58-4c9c-9f73-6a5c2a8d5011)

**Comment by stapelberg** [comment]
You’re in the wrong place, sorry.
